spring:  
  application:  
      name: eureka-server 

security:   
  basic:  
    enabled: true
  user:  
    name: eureka
    password: chunze1qaz2wsx  
      
server:  
  port: 8761  
    
eureka:  
  instance:   
   hostname: 10.81.29.214
   prefer-ip-address: true
   instance-id: fastdfs.chunzeacademy.com:${server.port}
  client:  
    register-with-eureka: true
    fetch-registry: true  
    service-url:  
      defaultZone: http://eureka:chunze1qaz2wsx@172.17.0.143:8761/eureka  
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000
      